# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 697b6e30b010eca0727445de320a2742248ac4c26d7f88e50b538e489b3758ef195ce46bdcf2141c2a22ebdd4894e322861867250009f9aeab451e039c9337c9

test:
  secret_key_base: a565e7e47f8737565047a9637c33d024cb698f582278e5f6f4187e55915b1be48f2ca8939c6849267432d9834846b0a23359b2f64c4c052b4215352114e238d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
